{
 "title": "India Coronavirus Statewise Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "label_values(india_coronavirus_confirmed, state)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "india_coronavirus_confirmed{state=\"$state\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "india_coronavirus_indians{state=\"$state\"}",
     "legendFormat": "Indians"
    },
    {
     "expr": "india_coronavirus_foreigners{state=\"$state\"}",
     "legendFormat": "Foreigners"
    }
   ]
  },
  {
   "title": "Last Update Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    { "expr": "india_stats_last_update" }
   ]
  },
  {
   "title": "Active Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "india_coronavirus_active{state=\"$state\"}"
    }
   ]
  },
  {
   "title": "% of Total Indian Active Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "india_coronavirus_active{state=\"$state\"} / on(job) india_coronavirus_total_active * 100"
    }
   ]
  },
  {
   "title": "% of Total Indian Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "india_coronavirus_confirmed{state=\"$state\"} / on(job) india_coronavirus_total_confirmed * 100"
    }
   ]
  },
  {
   "title": "Recovered Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "india_coronavirus_recovered{state=\"$state\"}"
    }
   ]
  },
  {
   "title": "% of Total Indian Recovered Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "india_coronavirus_recovered{state=\"$state\"} / on(job) india_coronavirus_total_recovered * 100"
    }
   ]
  },
  {
   "title": "Trends ($state)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "india_coronavirus_confirmed{state=\"$state\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "india_coronavirus_active{state=\"$state\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "india_coronavirus_recovered{state=\"$state\"}",
     "legendFormat": "Recovered"
    },
    {
     "expr": "increase(india_coronavirus_deaths{state=\"$state\"}[1h])",
     "legendFormat": "Deaths"
    }
   ]
  },
  {
   "title": "Death Cases ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "india_coronavirus_deaths{state=\"$state\"}"
    }
   ]
  },
  {
   "title": "% of Total Indian Deaths ($state)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "india_coronavirus_deaths{state=\"$state\"} / on(job) india_coronavirus_total_deaths * 100"
    }
   ]
  },
  {
   "title": "Total Cases",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, india_coronavirus_confirmed))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Death Cases",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, india_coronavirus_deaths))",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}