{
 "title": "Realtime COVID 19 Dashboard (World and Countrywise Stats)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "label_values(coronavirus_active_cases, country)"
   },
   {
    "name": "duration",
    "query": "1m,5m,15m,30m,1h,3h,6h,12h,24h,1w,2w"
   }
  ]
 },
 "panels": [
  {
   "title": "Read This",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "The code behind this dashboard can be found at https://github.com/nabarunchatterjee/corona\n\nUsage: The data for a different country can be found by changing the country variable at the top of the page.\n\nThe data presented here is a representation of the data pulled from the api present at https://rapidapi.com/astsiatsko/api/coronavirus-monitor/endpoints\n\n"
  },
  {
   "title": "Countrywise Stats (Change country at the  top of the page) [Click to expand/fold]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Total Cases ($country)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "coronavirus_cases{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset $duration",
     "legendFormat": "{{$duration}} ago"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} - (coronavirus_cases{country=\"$country\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "Total Deaths ($country)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "coronavirus_deaths{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset $duration",
     "legendFormat": "$duration ago"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} - (coronavirus_deaths{country=\"$country\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "Active Cases ($country)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "coronavirus_active_cases{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_active_cases{country=\"$country\"} offset $duration",
     "legendFormat": "{{$duration}} ago"
    },
    {
     "expr": "coronavirus_active_cases{country=\"$country\"} - (coronavirus_active_cases{country=\"$country\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "Total Recovered ($country)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset $duration",
     "legendFormat": "$duration ago"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} - (coronavirus_total_recovered{country=\"$country\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "Cases/1million population ($country)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "coronavirus_total_cases_per_1m_population{country=\"$country\"}",
     "legendFormat": "Now"
    }
   ]
  },
  {
   "title": "Seriously Critical Cases ($country)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "coronavirus_serious_critical{country=\"$country\"}",
     "legendFormat": "Now"
    }
   ]
  },
  {
   "title": "$country Total Cases Trends",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "coronavirus_cases{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset 24h",
     "legendFormat": "1d ago"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset 48h",
     "legendFormat": "2d ago"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset 72h",
     "legendFormat": "3d ago"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset 96h",
     "legendFormat": "4d ago"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset 120h",
     "legendFormat": "5d ago"
    },
    {
     "expr": "coronavirus_cases{country=\"$country\"} offset 144h",
     "legendFormat": "6d ago"
    }
   ]
  },
  {
   "title": "$country Deaths Trends",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "coronavirus_deaths{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset 24h",
     "legendFormat": "1d ago"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset 48h",
     "legendFormat": "2d ago"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset 72h",
     "legendFormat": "3d ago"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset 96h",
     "legendFormat": "4d ago"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset 120h",
     "legendFormat": "5d ago"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"} offset 144h",
     "legendFormat": "6d ago"
    }
   ]
  },
  {
   "title": "$country Recovered Trends",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset 24h",
     "legendFormat": "1d ago"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset 48h",
     "legendFormat": "2d ago"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset 72h",
     "legendFormat": "3d  ago"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset 96h",
     "legendFormat": "4d ago"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset 120h",
     "legendFormat": "5d ago"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"} offset 144h",
     "legendFormat": "6d ago"
    }
   ]
  },
  {
   "title": "$country Trend (Linear)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coronavirus_cases{country=\"$country\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"}",
     "legendFormat": "Deaths"
    },
    {
     "expr": "coronavirus_active_cases{country=\"$country\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"}",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "$country Trend (Logarithmic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coronavirus_cases{country=\"$country\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "coronavirus_deaths{country=\"$country\"}",
     "legendFormat": "Deaths"
    },
    {
     "expr": "coronavirus_active_cases{country=\"$country\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "coronavirus_total_recovered{country=\"$country\"}",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "World Stats (Click To Expand/Fold)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Total Cases (World)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "coronavirus_total_cases{region=\"world\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_total_cases{region=\"world\"} offset $duration",
     "legendFormat": "$duration ago"
    },
    {
     "expr": "coronavirus_total_cases{region=\"world\"} - (coronavirus_total_cases{region=\"world\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "Total Deaths (World)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "coronavirus_total_deaths{region=\"world\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_total_deaths{region=\"world\"} offset $duration",
     "legendFormat": "$duration ago"
    },
    {
     "expr": "coronavirus_total_deaths{region=\"world\"} - (coronavirus_total_deaths{region=\"world\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "Total Recovered (World)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "coronavirus_total_recovered{region=\"world\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset $duration",
     "legendFormat": "$duration ago"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} - (coronavirus_total_recovered{region=\"world\"} offset $duration)",
     "legendFormat": "Increase"
    }
   ]
  },
  {
   "title": "World Trend Total Cases",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    { "expr": "coronavirus_total_cases", "legendFormat": "Now" },
    {
     "expr": "coronavirus_total_cases offset 24h",
     "legendFormat": "1d ago"
    },
    {
     "expr": "coronavirus_total_cases offset 48h",
     "legendFormat": "2d ago"
    },
    {
     "expr": "coronavirus_total_cases offset 72h",
     "legendFormat": "3d ago"
    },
    {
     "expr": "coronavirus_total_cases offset 96h",
     "legendFormat": "4d ago"
    },
    {
     "expr": "coronavirus_total_cases offset 120h",
     "legendFormat": "5d ago"
    },
    {
     "expr": "coronavirus_total_cases offset 144h",
     "legendFormat": "6d ago"
    }
   ]
  },
  {
   "title": "World Trend Deaths",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    { "expr": "coronavirus_total_deaths", "legendFormat": "Now" },
    {
     "expr": "coronavirus_total_deaths offset 24h",
     "legendFormat": "1d ago"
    },
    {
     "expr": "coronavirus_total_deaths offset 48h",
     "legendFormat": "2d ago"
    },
    {
     "expr": "coronavirus_total_deaths offset 72h",
     "legendFormat": "3d ago"
    },
    {
     "expr": "coronavirus_total_deaths offset 96h",
     "legendFormat": "4d ago"
    },
    {
     "expr": "coronavirus_total_deaths offset 120h",
     "legendFormat": "5d ago"
    },
    {
     "expr": "coronavirus_total_deaths offset 144h",
     "legendFormat": "6d ago"
    }
   ]
  },
  {
   "title": "World Trend Recovered",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "coronavirus_total_recovered{region=\"world\"}",
     "legendFormat": "Now"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset 24h",
     "legendFormat": "1d ago"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset 48h",
     "legendFormat": "2d ago"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset 72h",
     "legendFormat": "3d ago"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset 96h",
     "legendFormat": "4d ago"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset 120h",
     "legendFormat": "5d ago"
    },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"} offset 144h",
     "legendFormat": "6d ago"
    }
   ]
  },
  {
   "title": "World Trend (Linear)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "coronavirus_total_cases", "legendFormat": "Total" },
    { "expr": "coronavirus_total_deaths", "legendFormat": "Deaths" },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"}",
     "legendFormat": "Recovered"
    }
   ]
  },
  {
   "title": "World Trend (Logarithmic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "coronavirus_total_cases", "legendFormat": "Total" },
    { "expr": "coronavirus_total_deaths", "legendFormat": "Deaths" },
    {
     "expr": "coronavirus_total_recovered{region=\"world\"}",
     "legendFormat": "Recovered"
    }
   ]
  },
  { "title": "Top 10 (Click to expand/fold)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Cases",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, coronavirus_cases))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Active Cases",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, coronavirus_active_cases))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, coronavirus_total_recovered{region=\"\"}))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, coronavirus_deaths))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Cases/ 1 million",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, coronavirus_total_cases_per_1m_population))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Increase in Total Cases in $duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, (sum by (country) (coronavirus_cases)) - (sum by (country) (coronavirus_cases offset $duration))))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  { "title": "World Map", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "World Map(Active Cases) ",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 79 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (code) (coronavirus_active_cases)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}